name: Tests

on:
  push:
    branches:
      - master
      - develop
  pull_request:
  release:
    types:
      - created


jobs:

  tests:
    name: PHPUnit
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install dependencies
        if: steps.composer-cache.outputs.cache-hit != 'true'
        run: composer install --prefer-dist --no-progress --no-suggest


  code-style:  # Check Coding standard - config defined in .php_cs(.dist)
    name: PHP CS Fixer
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: docker://oskarstark/php-cs-fixer-ga:latest
        with:
          args: --diff --dry-run --allow-risky=yes --verbose --format=txt